[book]
authors = ["Minoru Osuka"]
language = "en"
multilingual = false
src = "src"
title = "Litsea Documentation"
description = "Documentation for Litsea - a compact word segmentation library in Rust"

[build]
build-dir = "../target/docs/en"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/mosuka/litsea"
edit-url-template = "https://github.com/mosuka/litsea/edit/main/docs/{path}"
no-section-label = false
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
